# Generated by Django 5.2.8 on 2026-02-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="-"),
        ),
    ]
