# Generated by Django 5.2.8 on 2026-02-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_address_zip_product_slug"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="Store_custo_last_na_6d3fa0_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customer",
            table="Store_customers",
        ),
    ]
