# Generated by Django 5.2.8 on 2026-02-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_customer_store_custo_last_na_6d3fa0_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customer",
            new_name="store_custo_last_na_2e448d_idx",
            old_name="Store_custo_last_na_6d3fa0_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
